[package]
name = "dev-csr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dev-csr-macro = { version = "0.1.0", path = "../dev-csr-macro" }
